language: python
dist: focal
python:
  - "3.8"
  - "3.9"
arch: amd64
os: linux
sudo: false
cache:
  pip: true
env:
  global:
    - PERLMUTTER_SIM=1
    - NERSC_HOST=perlmutter
    - SLURM_CONSTRAINT=cpu
    - OMP_NUM_THREADS=4
  jobs:
    - CONFIG=cpu
    - CONFIG=gpu
branches:
  only:
    - master
    - main
    - develop
addons:
  apt:
    update: true
    packages:
      - cmake
      - libopenmpi-dev
      - openmpi-bin
before_install:
  - echo "Setting up Perlmutter environment"
install:
  - pip install pytest numpy
  - mkdir -p $HOME/.local/bin
  - echo "#!/bin/bash" > $HOME/.local/bin/module
  - echo "echo Module command executed" >> $HOME/.local/bin/module
  - chmod +x $HOME/.local/bin/module
  - export PATH=$HOME/.local/bin:$PATH
before_script:
  - echo "#!/bin/bash" > mpi_job.slurm
  - echo "#SBATCH -C cpu" >> mpi_job.slurm
  - echo "#SBATCH -t 01:00:00" >> mpi_job.slurm
  - echo "#SBATCH -N 1" >> mpi_job.slurm
  - echo "source mpi_env" >> mpi_job.slurm
  - echo "srun python mpi_script.py" >> mpi_job.slurm
  - echo "# MPI environment settings" > mpi_env
  - echo "export MPICH_GPU_SUPPORT_ENABLED=1" >> mpi_env
  - echo "print('MPI script')" > mpi_script.py
script:
  - echo "Running tests in Perlmutter simulation mode"
  - module list || true
  - echo "Validating Slurm script"
  - grep -q "mpi_env" mpi_job.slurm && echo "Found mpi_env in slurm script" || echo "Warning: not found"
  - python -c "print('Test passed')"
  - exit 0
